# Generated by Django 5.2.1 on 2025-05-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
